# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!



def shared_pods
platform :ios, '16.0'
    pod 'YPImagePicker', :path => "./Components/YPImagePicker-master"
    pod 'CryptoSwift', :path => "./Components/CryptoSwift-main"
    pod 'ProgressHUD'
    pod 'FMDB', :path => 'Components/fmdb'
    pod 'EasyMapping', :path => 'Components/EasyMapping'
    pod 'SwiftReflection', :path => 'Components/SwiftReflection'
    pod 'CocoaLumberjack', :path => 'Components/CocoaLumberjack'
    pod 'MTDates'
    pod 'libextobjc'
end

target 'CalendarApp' do
    shared_pods
end
