# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!



def shared_pods
platform :ios, '16.0'
    pod 'YPImagePicker', :path => "./Components/YPImagePicker-master"
    pod 'CryptoSwift', :path => "./Components/CryptoSwift-main"
    pod 'ProgressHUD'
end

target 'CalendarApp' do
    shared_pods
end
